<?xml version="1.0" encoding="utf-8"?><Database Name="Parking" Class="DataModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=Parking;Integrated Security=True" SettingsObjectName="Parking.Properties.Settings" SettingsPropertyName="ParkingConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="parking.BlackoutDates" Member="BlackoutDates">
    <Type Name="BlackoutDate">
      <Column Name="DateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BlackoutDate" Member="BlackoutDate1" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="parking.ParkingSpaces" Member="ParkingSpaces">
    <Type Name="ParkingSpace">
      <Column Name="ParkingSpaceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PlaceRentedFor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParkingSpacesOwnerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="parking.ParkingSpacesAdministrator" Member="ParkingSpacesAdministrators">
    <Type Name="ParkingSpacesAdministrator">
      <Column Name="AdministratorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdministratorName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="StartsOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndsOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="parking.ParkingSpacesOwners" Member="ParkingSpacesOwners">
    <Type Name="ParkingSpacesOwner">
      <Column Name="OwnerID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OwnerName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SpaceNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartsOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EndsOn" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="parking.usp_FreeParkingSpaces_AddNew" Method="usp_FreeParkingSpaces_AddNew">
    <Parameter Name="ownerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="date_start" Type="System.DateTime" DbType="Date" />
    <Parameter Name="date_end" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
</Database>