#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Database.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parking")]
	public partial class DataModelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataModelDataContext() : 
				base(global::Parking.Properties.Settings.Default.ParkingConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataModelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataModelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BlackoutDate> BlackoutDates
		{
			get
			{
				return this.GetTable<BlackoutDate>();
			}
		}
		
		public System.Data.Linq.Table<ParkingSpacesAdministrator> ParkingSpacesAdministrators
		{
			get
			{
				return this.GetTable<ParkingSpacesAdministrator>();
			}
		}
		
		public System.Data.Linq.Table<ParkingSpacesOwner> ParkingSpacesOwners
		{
			get
			{
				return this.GetTable<ParkingSpacesOwner>();
			}
		}
		
		public System.Data.Linq.Table<ParkingSpace> ParkingSpaces
		{
			get
			{
				return this.GetTable<ParkingSpace>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="parking.usp_BlackoutDates_AddNew")]
		public int usp_BlackoutDates_AddNew([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="parking.usp_BlackoutDates_Delete")]
		public int usp_BlackoutDates_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), date);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="parking.usp_ParkingSpacesOwners_AddNew")]
		public int usp_ParkingSpacesOwners_AddNew([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string owner, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> space)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), owner, space);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="parking.usp_ParkingSpacesOwners_Delete")]
		public int usp_ParkingSpacesOwners_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OwnerID", DbType="Int")] System.Nullable<int> ownerID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ownerID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="parking.usp_AddFreeParkingSpaces")]
		public int usp_AddFreeParkingSpaces([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ownerId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date_start, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date_end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ownerId, date_start, date_end);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="parking.BlackoutDates")]
	public partial class BlackoutDate
	{
		
		private System.DateTime _Date;
		
		public BlackoutDate()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="parking.ParkingSpacesAdministrator")]
	public partial class ParkingSpacesAdministrator
	{
		
		private string _AdministratorName;
		
		private System.DateTime _StartsOn;
		
		private System.DateTime _EndsOn;
		
		public ParkingSpacesAdministrator()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdministratorName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string AdministratorName
		{
			get
			{
				return this._AdministratorName;
			}
			set
			{
				if ((this._AdministratorName != value))
				{
					this._AdministratorName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartsOn", DbType="DateTime NOT NULL")]
		public System.DateTime StartsOn
		{
			get
			{
				return this._StartsOn;
			}
			set
			{
				if ((this._StartsOn != value))
				{
					this._StartsOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndsOn", DbType="DateTime NOT NULL")]
		public System.DateTime EndsOn
		{
			get
			{
				return this._EndsOn;
			}
			set
			{
				if ((this._EndsOn != value))
				{
					this._EndsOn = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="parking.ParkingSpacesOwners")]
	public partial class ParkingSpacesOwner
	{
		
		private int _OwnerID;
		
		private string _OwnerName;
		
		private System.Nullable<int> _SpaceNumber;
		
		private System.DateTime _StartsOn;
		
		private System.DateTime _EndsOn;
		
		public ParkingSpacesOwner()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int OwnerID
		{
			get
			{
				return this._OwnerID;
			}
			set
			{
				if ((this._OwnerID != value))
				{
					this._OwnerID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OwnerName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string OwnerName
		{
			get
			{
				return this._OwnerName;
			}
			set
			{
				if ((this._OwnerName != value))
				{
					this._OwnerName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpaceNumber", DbType="Int")]
		public System.Nullable<int> SpaceNumber
		{
			get
			{
				return this._SpaceNumber;
			}
			set
			{
				if ((this._SpaceNumber != value))
				{
					this._SpaceNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartsOn", DbType="DateTime NOT NULL")]
		public System.DateTime StartsOn
		{
			get
			{
				return this._StartsOn;
			}
			set
			{
				if ((this._StartsOn != value))
				{
					this._StartsOn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndsOn", DbType="DateTime NOT NULL")]
		public System.DateTime EndsOn
		{
			get
			{
				return this._EndsOn;
			}
			set
			{
				if ((this._EndsOn != value))
				{
					this._EndsOn = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="parking.ParkingSpaces")]
	public partial class ParkingSpace
	{
		
		private System.DateTime _Date;
		
		private System.Nullable<int> _PlaceRentedFor;
		
		private System.Nullable<int> _ParkingSpacesOwnerID;
		
		public ParkingSpace()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlaceRentedFor", DbType="Int")]
		public System.Nullable<int> PlaceRentedFor
		{
			get
			{
				return this._PlaceRentedFor;
			}
			set
			{
				if ((this._PlaceRentedFor != value))
				{
					this._PlaceRentedFor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParkingSpacesOwnerID", DbType="Int")]
		public System.Nullable<int> ParkingSpacesOwnerID
		{
			get
			{
				return this._ParkingSpacesOwnerID;
			}
			set
			{
				if ((this._ParkingSpacesOwnerID != value))
				{
					this._ParkingSpacesOwnerID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
