//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpace
    {
        public int ParkingSpaceId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> PlaceRentedFor { get; set; }
        public Nullable<int> ParkingSpaceOwnerID { get; set; }
        public Nullable<System.DateTime> Added { get; set; }
        public Nullable<System.DateTime> PlaceRentedDate { get; set; }
    }
}
