//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpaceGuest
    {
        public int GuestId { get; set; }
        public int ParkingSpaceOwnerID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public string EmailSentBy { get; set; }
    }
}
