//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingSpaceOwner
    {
        public int ParkingSpaceOwnerID { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> SpaceNumber { get; set; }
        public System.DateTime StartsOn { get; set; }
        public System.DateTime EndsOn { get; set; }
    }
}
