CREATE TABLE [parking].[ParkingSpacesAdministrator](
	[AdministratorId] [INT] IDENTITY(1,1) NOT NULL,
	[AdministratorName] [NVARCHAR](100) NOT NULL,
	[StartsOn] [DATETIME] NOT NULL,
	[EndsOn] [DATETIME] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AdministratorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO