CREATE TABLE [parking].[ParkingSpaceGuest](
	[GuestId] [INT] IDENTITY(1,1) NOT NULL,
	[ParkingSpaceOwnerID] INT NOT NULL,
	[Name] [NVARCHAR](100) NOT NULL,
	[EmailSentBy] VARCHAR(100) null,
	[Date] [DATETIME] NOT NULL DEFAULT getdate(),
PRIMARY KEY CLUSTERED 
(
	[GuestId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

